workflows:
  build-debug-apk:
    name: Build Debug APK
    max_build_duration: 15
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
